### PR TITLE
Support for OCaml 5.0 and latest menhir, move to github actions

### PR DESCRIPTION
**Pull request by eilvelia**
_Update:_ To add a bit more information about this pull request:

- The Stream module is deprecated in OCaml 4.14 and removed in OCaml 5.0, I replaced it with [Seq](https://v2.ocaml.org/api/Seq.html). The same change was made in yojson. Seq is only available since OCaml 4.07, so support for older versions is dropped. OCaml libraries usually support OCaml 4.08 and newer nowadays.
- Latest versions of menhir require `(using menhir 2.0)` or above in the dune file (edn is [constrained](https://github.com/ocaml/opam-repository/blob/24f30611d76ac37e7985d9f19068653dd93ba63b/packages/edn/edn.0.1.6-1-gff9db95/opam#L16) in the opam repository currently) to work without explicit type annotations.
- Since Travis is dead, I moved CI to GitHub (there's also convenient `ocaml/setup-ocaml` for GitHub Actions, and it's easier to run CI in forks).

### CODE REVIEW

**Comment by prepor** [comment]
Hi @Bannerets! Thank you for keeping this lib alive! Shouldn't we have Github Action running for this PR?

**Comment by eilvelia** [comment]
> Hi @Bannerets! Thank you for keeping this lib alive! Shouldn't we have Github Action running for this PR?

Hi! :). Oh, I think Github Actions will be activated for pull requests only after it is merged to master. (Also, by default on GitHub, actions for PRs by first-time contributors should be manually allowed to run by clicking a button on the PR page.)

But you can see that the action was run on my fork: https://github.com/Bannerets/ocaml-edn/commits/work (https://github.com/Bannerets/ocaml-edn/actions/runs/3237780142)

**Comment by prepor** [comment]
Thank you again! I added you to Collaborators for this repository.

**Comment by eilvelia** [comment]
> I added you to Collaborators for this repository.

Thank you! I will then make a v0.2.0 release.

**Pull request merged**
